inputs:
  IMAGE_REPOSITORY:
    required: true
  BUILD_CONTEXT:
    required: true
  BUILD_TARGET:
    description: "Sets the target stage to build"
    required: false
  IMAGE_NAME:
    required: true
  REGISTRY_JSON_KEY:
    required: true
  SECURITY_SCAN:
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
  - name: Check inputs
    shell: bash
    run: |
      if [ -z "${{inputs.IMAGE_REPOSITORY}}" ]; then echo "inputs.IMAGE_REPOSITORY is missing"; exit=1; fi
      if [ -z "${{inputs.BUILD_CONTEXT}}" ]; then echo "inputs.BUILD_CONTEXT is missing"; exit=1; fi
      if [ -z "${{inputs.IMAGE_NAME}}" ]; then echo "inputs.IMAGE_NAME is missing"; exit=1; fi
      if [ -z "${{inputs.REGISTRY_JSON_KEY}}" ]; then echo "inputs.REGISTRY_JSON_KEY is missing"; exit=1; fi
      if [ -n "$exit" ]; then exit 1; fi

  - name: Checkout code
    uses: actions/checkout@v2
    
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: ${{ inputs.IMAGE_REPOSITORY }}/${{inputs.IMAGE_NAME}}
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha

  - name: Set up Docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@v1

  - name: Login to registry
    uses: docker/login-action@v1
    with:
      registry: ${{ inputs.IMAGE_REPOSITORY }}
      username: _json_key
      password: ${{ inputs.REGISTRY_JSON_KEY }}
    
  - name: Build image localy first
    uses: docker/build-push-action@v2
    id: docker_build
    with:
      context: ${{inputs.BUILD_CONTEXT}}
      tags: local
      pull: true
      target: ${{ inputs.BUILD_TARGET }}
      load: true
      cache-from: type=registry,ref=${{ inputs.IMAGE_REPOSITORY }}/${{inputs.IMAGE_NAME}}:buildcache
      cache-to: type=registry,ref=${{ inputs.IMAGE_REPOSITORY }}/${{inputs.IMAGE_NAME}}:buildcache

  - name: create empty .trivyignore if file is missing
    shell: bash
    run: touch .trivyignore

  - name: Run Trivy vulnerability scanner
    if: ${{ inputs.SECURITY_SCAN == true }}
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: local
      format: 'table'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'
      trivyignores: .trivyignore

  - name: Build image and push to registry
    uses: docker/build-push-action@v2
    id: docker_build_push
    with:
      context: ${{inputs.BUILD_CONTEXT}} 
      tags: ${{ steps.meta.outputs.tags }}
      target: ${{ inputs.BUILD_TARGET }}
      push: true
      pull: true
      cache-from: type=registry,ref=${{ inputs.IMAGE_REPOSITORY }}/${{inputs.IMAGE_NAME}}:buildcache
      cache-to: type=registry,ref=${{ inputs.IMAGE_REPOSITORY }}/${{inputs.IMAGE_NAME}}:buildcache

  - name: Image digest
    shell: bash
    run: echo ${{ steps.docker_build_push.outputs.digest }}
